import React, {useContext, useState} from "react";
import style from './Signup.module.css';

import { AuthContext } from "../../Context/AuthContext";
import axios from "axios";
import { NavLink } from "react-router-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRightFromBracket, faListCheck, faRightFromBracket, faSquare, faSquareCheck } from "@fortawesome/free-solid-svg-icons";

const Signin = () => {
    const auth = useContext(AuthContext);
    let [step, setStep] = useState(0);
    let [avatar, setAvatar] = useState('');

    let [state, setState] = useState({
        inputs: {
            Name: {
                value: '',
            },
            Email: {
                value: '',
            },
            Password: {
                value: '',
            },
            confirmPassword: {
                value: '',
            },
        }
    })

    const nextStepHandler = () => {
        let updatedStep = step;
        if(updatedStep === 2) return
        updatedStep = updatedStep + 1;
        setStep(updatedStep)
    }

    const prevStepHandler = () => {
        let updatedStep = step;
        if(updatedStep === 0) return
        updatedStep = updatedStep - 1;
        setStep(updatedStep)
    }

    const changeHandler = (event, fieldName) => {
        let value = event.target.value;
        // let newState = {...state};

        // newState.inputs[fieldName].value = value;
        // setState(newState);
        setAvatar(value)
    }

    const regiserHandler = (event) => {
        event.preventDefault();
        let data = {
            name: state.inputs.Name.value, 
            email: state.inputs.Email.value,
            password: state.inputs.Password.value,
            confirmPass: state.inputs.confirmPassword.value,
        };

        axios.post('http://localhost:8000/Auth/signup', data)
        .then(response => {
            console.log(response)
        })
        .catch(err => console.log(err));
    }


    return (
        <div className={style.Signup}>
            {/* NAVBAR */}
            <div className={style.navBar}>
                <div className={style.title}>
                    <div className={style.icon}><img src={process.env.PUBLIC_URL + 'bot.png'}/></div>
                    <div className={style.title1}>ChatBot</div>
                    <div className={style.title2}>Signup</div>
                </div>
            </div>
            {/* STEPPER COMPONENT */}
            <form className={style.stepperForm}>
                <div className={style.firstHeader}>
                    <div className={style.firstHeaderBuble} style={{background: step <= 2 ? '#E5AD06' : '#a6a6a6'}}>1</div>
                    <div className={style.firstHeaderText} style={{color: step === 0 ? '#384850' : '#a6a6a6'}}>Avatar</div>
                </div>
                <div className={style.firstBody}
                style={{
                    height: step !== 0 ? '20px' : '100px',
                }}>
                    {step === 0 && (<>
                    <div className={style.firstDescription}>Auto-Generated by the name you pick</div>
                    <div className={style.firstInputComp}>
                        <img alt="" src={'https://robohash.org/' + avatar}/>
                        <input type="text" value={avatar} placeholder="Name" onChange={(e) => changeHandler(e, 'Name')}/>
                    </div>
                    </>)}
                </div>

                <div className={style.secondHeader}>
                    <div className={style.secondHeaderBuble} style={{background: step >= 1 ? '#E5AD06' : '#a6a6a6'}}>2</div>
                    <div className={style.secondHeaderText} style={{color: step === 1 ? '#384850' : '#a6a6a6'}}>Email</div>
                </div>
                <div className={style.secondBody}
                style={{
                    height: step !== 1 ? '20px' : '80px',
                }}>
                    {step === 1 && (<>
                    <div className={style.secondDescription}>Choose an email</div>
                    <div className={style.secondInputComp}>
                        <input type="email" placeholder="example@gmail.com"/>
                    </div>
                    </>)}
                </div>

                <div className={style.thirdHeader}>
                    <div className={style.thirdHeaderBuble} style={{background: step === 2 ? '#E5AD06' : '#a6a6a6'}}>3</div>
                    <div className={style.thirdHeaderText} style={{color: step === 2 ? '#384850' : '#a6a6a6'}}>Password</div>
                </div>
                <div className={style.thirdBody}
                style={{
                    height: step !== 2 ? '20px' : '120px',
                    borderLeft : step !== 2 ? 'none' : '2px',
                }}>
                    {step === 2 && (<>
                    <div className={style.thirdDescription}>Type a valid password</div>
                    <div className={style.thirdInputComp}>
                        <input type="password" placeholder="Password"/>
                        <input type="password" placeholder="Confirm Password"/>
                    </div>
                    </>)}
                </div>
            </form>
                <div className={style.ButtonSection}>
                    <button 
                    className={style.back} 
                    onClick={prevStepHandler}
                    style={{
                        color: step === 0 ? '#a6a6a6' : '#384850',
                        cursor: step === 0 ? 'not-allowed' : 'pointer',
                    }}>Back</button>
                    <button className={style.continue} 
                    onClick={nextStepHandler}>Continue</button>
                </div>
        </div>
    )
}

export default Signin;


// "#1ccc0f" green